FROM golang:1.20 AS builder
# Next line is just for debug
WORKDIR /build

COPY cmd/mailing-api/main.go cmd/mailing-api/main.go
COPY pkg/mailing pkg/mailing
COPY shared/ shared/

COPY go.mod go.sum ./
RUN go mod download && go mod verify
WORKDIR /build/cmd/mailing-api
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-binary

# Production phase
FROM alpine:3.14
# Next line is just for debug
WORKDIR /app
COPY --from=builder /build/cmd/mailing-api/go-binary .

CMD ["ls", "-la", "./build"]